

#ifndef GLOBALDEFINITIONS_H
#define GLOBALDEFINITIONS_H


//RENDER


#define SCREEN_TEXTURE_POSITION 0xC014 //PRECALCULAR VMEM_POS

#define SCREEN_TEXTURE_BUFFER 0x1C40 //MAP_MEM + MAP_SIZE
#define SCREEN_TEXTURE_HEIGHT 100
#define SCREEN_TEXTURE_WIDTH 80
#define SCREEN_TEXTURE_WIDTH_HALF 40
#define SCREEN_TEXTURE_WIDTH_BYTES 40

#define CELLS_IN_VIEW_ARRAY 0x2BE0 //SCREEN_TEXTURE_BUFFER + SCREEN_TEXTURE_WIDTH_BYTES*SCREEN_TEXTURE_HEIGHT

#define SCREEN_TEXTURE_GROUND_SKY_SIZE (SCREEN_TEXTURE_WIDTH_BYTES*(SCREEN_TEXTURE_HEIGHT/2-1))

#define SCREEN_TEXTURE_HORIZON_WALL_SIZE (2*SCREEN_TEXTURE_WIDTH_BYTES)
#define SCREEN_TEXTURE_HORIZON_WALL_START (SCREEN_TEXTURE_BUFFER+SCREEN_TEXTURE_GROUND_SKY_SIZE)

#define SCREEN_TEXTURE_GROUND_START (SCREEN_TEXTURE_HORIZON_WALL_START+SCREEN_TEXTURE_HORIZON_WALL_SIZE)


#define MAP_MEM  0x0040
#define MAP_HEIGHT 32
#define MAP_WIDTH 32
#define MAP_SIZE 1024

#define GENERATOR_DATA_PTR 0x1C40 //MAP_MEM + MAP_SIZE
#define GENERATOR_DATA_END_PTR 0x2C40 //MAP_MEM + 4096 bytes

#define MINIMAP_POSITION 0xC570 //PRECALCULAR VMEM_POS

#define COMPASS_POSITION 0xE434


#define MINIMAP_BUFFER 0x1C40 //MAP_MEM + MAP_SIZE
#define MINIMAP_HEIGHT 16
#define MINIMAP_HEIGHT_HALF 8
#define MINIMAP_HEIGHT_BYTES 64
#define MINIMAP_WIDTH 16
#define MINIMAP_WIDTH_HALF 8
#define MINIMAP_WIDTH_BYTES 16
#define MINIMAP_HEIGHT_WIDTH_RATIO 4

//MINIMAP COLORS

#define MINIMAP_WALL_COLOR 2
#define MINIMAP_FLOOR_COLOR 3
#define MINIMAP_PLAYER_COLOR 5

#define WALL1_COLOR 14
#define WALL2_COLOR 13
#define DOOR1_COLOR 12
#define DOOR2_COLOR 15

#define GROUND_COLOR 0
#define SKY_COLOR 1
#define HORIZON_COLOR 2


//TEXTURES

#define UNCOMPRESSED_LEVEL_TEXTURES 0x0840
#define UNCOMPRESSED_SHARED_TEXTURES 0x0440
//#define UNCOMPRESSED_NPC_TEXTURES

#define TEXTURE_WIDTH 32
#define TEXTURE_HEIGHT 32
#define TEXTURE_HEIGHT_HALF 16

#define COMPRESSED_TEXTURE_WIDTH_BYTES 16
#define COMPRESSED_TEXTURE_HEIGHT_BYTES 32

//MAP IDs

#define CELLTYPE_FLOOR 254
#define CELLTYPE_WALL1 0
#define CELLTYPE_WALL2 1
#define CELLTYPE_WALL3 2
#define CELLTYPE_WALL4 3
#define CELLTYPE_DOOR 4
#define CELLTYPE_UNDEFINED 255





#endif